services:
  app:
    build: .
    container_name: worker_factory_app
    command: >
      bash -c "alembic upgrade head &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs/" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent_code_shared:/app/agent_code_shared
    networks:
      - factory_net

  db:
    image: postgres:16-alpine
    container_name: worker_factory_db
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-worker_factory}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-worker_factory}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - factory_net


  redis:
    image: redis:7-alpine
    container_name: factory_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - factory_net


  celery:
    build: .
    container_name: factory_celery
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent_code_shared:/app/agent_code_shared
    env_file:
      - .env
    environment:
      - HOST_PROJECT_PATH=${HOST_PROJECT_PATH}
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
    networks:
      - factory_net
#
#
#  beat:
#    build: .
#    container_name: factory_beat
##    command: celery -A src.core.celery_app beat --loglevel=info
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - db
#    volumes:
#      - .:/app


volumes:
  postgres_data:
  redis_data:

networks:
  factory_net:
    # Фіксуємо ім'я мережі, щоб DockerService (Python) точно знав, куди підключати воркерів
    name: worker_factory_default